language: python

matrix:
  include:
    - os: linux
      env:
        - LUA="lua=5.1"
    - os: linux
      env:
        - LUA="lua=5.2"
    - os: linux
      env:
        - LUA="lua=5.3"
    - os: linux
      env:
        - LUA="luajit=2.0"
    - os: linux
      env:
        - LUA="luajit=2.1"

before_install:
  - git clone --depth 1 https://github.com/cehoffman/luaenv.git ~/.luaenv
  - export PATH="$HOME/.luaenv/bin:$PATH"
  - luaenv install $LUA

script:
    - lua test.lua