language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov
  - luarocks install tapered

script:
  - lua -lluacov test.lua

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 2ebd124e-c5be-4daa-8d5c-93586692ba3d